# documentation: https://taiga.io/docs/
# slogan: Taiga is an open-source project management tool for agile developers & designers.
# tags: taiga, project management, open source, agile, scrum, kanban

services:
  taiga-frontend:
    image: "taigaio/taiga-front:${SOFTWARE_VERSION_TAG}"
    volumes:
      - taiga-assets:/opt/data/assets
    depends_on:
      - taiga-backend
      - taiga-events
    environment:
      - TAIGA_URL=${BASE_URL}
      - TAIGA_WEBSOCKETS_URL=wss://${DOMAIN}
      - TAIGA_SUBPATH=""
      - PUBLIC_REGISTER_ENABLED=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 2s
      timeout: 10s
      retries: 15

  taiga-backend:
    image: "taigaio/taiga-back:${SOFTWARE_VERSION_TAG}"
    volumes:
      - taiga-assets:/opt/data/assets
    depends_on:
      - postgres
      - taiga-async-rabbitmq
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=${APP_PASSWORD}
      - POSTGRES_HOST=taiga-db
      - TAIGA_SECRET_KEY=${APP_PASSWORD}
      - TAIGA_SITES_SCHEME=https
      - TAIGA_SITES_DOMAIN=${DOMAIN}
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - DEFAULT_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - EMAIL_USE_TLS=false
      - EMAIL_USE_SSL=false
      - EMAIL_HOST=${SMTP_HOST}
      - EMAIL_PORT=${SMTP_PORT}
      - RABBITMQ_USER=taiga
      - RABBITMQ_PASS=${APP_PASSWORD}
      - PUBLIC_REGISTER_ENABLED=true
      - ENABLE_TELEMETRY=true
      - TAIGA_TELEMETRY_REFERER=elest.io
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000"]
      interval: 2s
      timeout: 10s
      retries: 15

  taiga-async:
    image: "taigaio/taiga-back:${SOFTWARE_VERSION_TAG}"
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    volumes:
      - taiga-assets:/opt/data/assets
    depends_on:
      - taiga-backend
      - taiga-async-rabbitmq
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=${APP_PASSWORD}
      - POSTGRES_HOST=taiga-db
      - TAIGA_SECRET_KEY=${APP_PASSWORD}
      - TAIGA_SITES_SCHEME=https
      - TAIGA_SITES_DOMAIN=${DOMAIN}
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - DEFAULT_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - EMAIL_USE_TLS=false
      - EMAIL_USE_SSL=false
      - EMAIL_HOST=${SMTP_HOST}
      - EMAIL_PORT=${SMTP_PORT}
      - RABBITMQ_USER=taiga
      - RABBITMQ_PASS=${APP_PASSWORD}
      - PUBLIC_REGISTER_ENABLED=true
      - ENABLE_TELEMETRY=true
      - TAIGA_TELEMETRY_REFERER=elest.io

  taiga-events:
    image: "taigaio/taiga-events:${SOFTWARE_VERSION_TAG}"
    depends_on:
      - taiga-events-rabbitmq
    environment:
      - RABBITMQ_USER=taiga
      - RABBITMQ_PASS=${APP_PASSWORD}
      - TAIGA_SECRET_KEY=${APP_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8888"]
      interval: 2s
      timeout: 10s
      retries: 15

  taiga-db:
    image: postgres:12.3
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=${APP_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 10

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret-erlang-cookie
      - RABBITMQ_DEFAULT_USER=taiga
      - RABBITMQ_DEFAULT_PASS=${APP_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=taiga
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 10

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret-erlang-cookie
      - RABBITMQ_DEFAULT_USER=taiga
      - RABBITMQ_DEFAULT_PASS=${APP_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=taiga
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 10

  taiga-protected:
    image: "taigaio/taiga-protected:${SOFTWARE_VERSION_TAG}"
    environment:
      - MAX_AGE=360
      - SECRET_KEY=${APP_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000"]
      interval: 2s
      timeout: 10s
      retries: 15

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "172.17.0.1:9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - ./taiga-static-data:/taiga/static
      - ./taiga-media-data:/taiga/media
    depends_on:
      - taiga-frontend
      - taiga-backend
      - taiga-events
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 2s
      timeout: 10s
      retries: 15

volumes:
  taiga-assets:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:
  taiga-static-data:
  taiga-media-data:
